### ISSUE TITLE
There are no TrainSplit and EvaluateSplit in data

### ISSUE THREAD

**Issue by Tambura** [ranjaykrishna/SST#2]
Hi! Thank you for your nice work!
It seems that it needs these two files in `data` to run the training.

**Comment by ranjaykrishna** [comment]
You should be able to download the features and the annotations from the ActivityNet website.

**Comment by Tambura** [comment]
I downloaded the features and annotations from the ActivityNet website and got two hdf5 files and some json files.
But the line 13 of `train.py`: `from data import TrainSplit, EvaluateSplit`
Does this mean you write two python scripts to split the dataset? There may be 2 class named `TrainSplit` and `EvaluateSplit` in these two scripts.

**Comment by Tambura** [comment]
PyCharm indexs the folder `data` firstly and do not search these two classes inside the `data.py`. So I get the wrong prompt. Maybe I need to configure the Pycharm. This is not an issue. Thank you!
